// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VCpuTop.h for the primary calling header

#ifndef VERILATED_VCPUTOP___024ROOT_H_
#define VERILATED_VCPUTOP___024ROOT_H_  // guard

#include "verilated.h"


class VCpuTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VCpuTop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_debug_valid,0,0);
        CData/*0:0*/ CpuTop__DOT___mem_io_in_ready;
        CData/*0:0*/ CpuTop__DOT___mem_io_out_valid;
        CData/*4:0*/ CpuTop__DOT___mem_io_out_bits_wb_addr;
        CData/*0:0*/ CpuTop__DOT___mem_io_out_bits_wb_en;
        CData/*0:0*/ CpuTop__DOT___exu_io_in_ready;
        CData/*0:0*/ CpuTop__DOT___exu_io_redirect_valid;
        CData/*0:0*/ CpuTop__DOT___idu_io_in_ready;
        CData/*3:0*/ CpuTop__DOT___idu_io_out_bits_alu_op;
        CData/*0:0*/ CpuTop__DOT__redirect_valid;
        CData/*0:0*/ CpuTop__DOT__reg_valid;
        CData/*0:0*/ CpuTop__DOT__ifu_io_out_ready;
        CData/*3:0*/ CpuTop__DOT__reg_1_alu_op;
        CData/*4:0*/ CpuTop__DOT__reg_1_wb_addr;
        CData/*0:0*/ CpuTop__DOT__reg_1_wb_en;
        CData/*1:0*/ CpuTop__DOT__reg_1_wb_sel;
        CData/*0:0*/ CpuTop__DOT__reg_1_mem_ren;
        CData/*0:0*/ CpuTop__DOT__reg_1_mem_wen;
        CData/*2:0*/ CpuTop__DOT__reg_1_mem_funct3;
        CData/*3:0*/ CpuTop__DOT__reg_1_mem_wmask;
        CData/*0:0*/ CpuTop__DOT__reg_1_csr_en;
        CData/*2:0*/ CpuTop__DOT__reg_1_csr_op;
        CData/*0:0*/ CpuTop__DOT__reg_1_is_jalr;
        CData/*0:0*/ CpuTop__DOT__reg_1_exception;
        CData/*3:0*/ CpuTop__DOT__reg_1_exception_cause;
        CData/*0:0*/ CpuTop__DOT__reg_1_mret;
        CData/*0:0*/ CpuTop__DOT__reg_valid_1;
        CData/*0:0*/ CpuTop__DOT__idu_io_out_ready;
        CData/*0:0*/ CpuTop__DOT__reg_2_mem_ren;
        CData/*0:0*/ CpuTop__DOT__reg_2_mem_wen;
        CData/*2:0*/ CpuTop__DOT__reg_2_mem_funct3;
        CData/*3:0*/ CpuTop__DOT__reg_2_mem_wmask;
        CData/*4:0*/ CpuTop__DOT__reg_2_wb_addr;
        CData/*0:0*/ CpuTop__DOT__reg_2_wb_en;
        CData/*1:0*/ CpuTop__DOT__reg_2_wb_sel;
        CData/*0:0*/ CpuTop__DOT__reg_valid_2;
        CData/*4:0*/ CpuTop__DOT__reg_3_wb_addr;
        CData/*0:0*/ CpuTop__DOT__reg_3_wb_en;
        CData/*0:0*/ CpuTop__DOT__reg_valid_3;
        CData/*0:0*/ CpuTop__DOT___reg_T;
        CData/*0:0*/ CpuTop__DOT___reg_T_1;
        CData/*0:0*/ CpuTop__DOT___reg_T_2;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT__io_out_valid;
        CData/*1:0*/ CpuTop__DOT__ifu__DOT__state;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT___GEN;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT___GEN_0;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT___GEN_1;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT___GEN_3;
        CData/*0:0*/ CpuTop__DOT__ifu__DOT___GEN_4;
        CData/*0:0*/ CpuTop__DOT__idu__DOT__io_reg_wen;
        CData/*0:0*/ CpuTop__DOT__idu__DOT__io_fwd_mem_wen;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___stall_T_1;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___stall_T_2;
        CData/*3:0*/ CpuTop__DOT__idu__DOT___GEN_3;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_9;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_16;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_17;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_19;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_20;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_22;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_24;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_25;
    };
    struct {
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_27;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_28;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_31;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_32;
        CData/*0:0*/ CpuTop__DOT__idu__DOT___GEN_33;
        CData/*0:0*/ CpuTop__DOT__idu__DOT__stall;
        CData/*0:0*/ CpuTop__DOT__idu__DOT____VdfgRegularize_h52656aab_0_10;
        CData/*0:0*/ CpuTop__DOT__idu__DOT____VdfgRegularize_h52656aab_0_11;
        CData/*0:0*/ CpuTop__DOT__idu__DOT____VdfgRegularize_h52656aab_0_13;
        CData/*0:0*/ CpuTop__DOT__idu__DOT__regfile__DOT___GEN;
        CData/*0:0*/ CpuTop__DOT__exu__DOT__io_fwd_wb_en;
        CData/*0:0*/ CpuTop__DOT__exu__DOT___GEN;
        CData/*0:0*/ CpuTop__DOT__exu__DOT___GEN_0;
        CData/*0:0*/ CpuTop__DOT__exu__DOT___io_fwd_wb_is_Load_T;
        CData/*1:0*/ CpuTop__DOT__mem__DOT__state;
        CData/*0:0*/ CpuTop__DOT__mem__DOT__reqReg_mem_ren;
        CData/*2:0*/ CpuTop__DOT__mem__DOT__reqReg_mem_funct3;
        CData/*3:0*/ CpuTop__DOT__mem__DOT__reqReg_mem_wmask;
        CData/*4:0*/ CpuTop__DOT__mem__DOT__reqReg_wb_addr;
        CData/*0:0*/ CpuTop__DOT__mem__DOT__reqReg_wb_en;
        CData/*1:0*/ CpuTop__DOT__mem__DOT__reqReg_wb_sel;
        CData/*1:0*/ CpuTop__DOT__mem__DOT__req_load_addr;
        CData/*0:0*/ CpuTop__DOT__mem__DOT__awSentReg;
        CData/*0:0*/ CpuTop__DOT__mem__DOT__wSentReg;
        CData/*0:0*/ CpuTop__DOT__mem__DOT___GEN_0;
        CData/*0:0*/ CpuTop__DOT__mem__DOT___GEN_3;
        CData/*0:0*/ CpuTop__DOT__mem__DOT___GEN_4;
        CData/*0:0*/ CpuTop__DOT__mem__DOT___GEN_5;
        CData/*1:0*/ CpuTop__DOT__mem__DOT__casez_tmp;
        CData/*7:0*/ CpuTop__DOT__mem__DOT__casez_tmp_0;
        CData/*0:0*/ CpuTop__DOT__mem__DOT___GEN_6;
        CData/*0:0*/ CpuTop__DOT__mem__DOT____VdfgRegularize_hc37f55c7_0_1;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_ifu_ar_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_ifu_r_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_ar_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_ar_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_r_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_r_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_aw_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_w_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_b_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_b_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_ar_id;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_r_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_r_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_aw_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_aw_ready;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_w_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_b_valid;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_b_ready;
        CData/*2:0*/ CpuTop__DOT__axiArbiter__DOT__state;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__readIdReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__awIdReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__awFullReg;
        CData/*3:0*/ CpuTop__DOT__axiArbiter__DOT__wStrbReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__wFullReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__awSentReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__wSentReg;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__memArFire;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__memAwFire;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__memWFire;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__axiAwFire;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__axiWFire;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__willBeWrite;
    };
    struct {
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_0;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_1;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_2;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_5;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_7;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_9;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_10;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_11;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_12;
        CData/*2:0*/ CpuTop__DOT__axiArbiter__DOT__casez_tmp;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT__axiArFire;
        CData/*2:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_15;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_16;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_17;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_18;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_19;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT___GEN_20;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT____VdfgRegularize_h6ac6c79f_0_1;
        CData/*0:0*/ CpuTop__DOT__axiArbiter__DOT____VdfgRegularize_h6ac6c79f_0_3;
        CData/*3:0*/ CpuTop__DOT__xbar__DOT__state;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__readIdReg;
        CData/*1:0*/ CpuTop__DOT__xbar__DOT__readTargetReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__awIdReg;
        CData/*1:0*/ CpuTop__DOT__xbar__DOT__awTargetReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__awFullReg;
        CData/*3:0*/ CpuTop__DOT__xbar__DOT__wStrbReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__wFullReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__awSentReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__wSentReg;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT__willBeWrite;
        CData/*1:0*/ CpuTop__DOT__xbar__DOT__target;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_2;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_3;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_6;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_7;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_8;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_9;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_10;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_11;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_13;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_14;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_15;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_16;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_18;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_19;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_20;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_21;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_22;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_23;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_24;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_25;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_26;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_27;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_28;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_29;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT___GEN_30;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_1;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_2;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_4;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_5;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_6;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_7;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_11;
    };
    struct {
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_12;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_13;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_14;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_15;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_16;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_17;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_18;
        CData/*0:0*/ CpuTop__DOT__xbar__DOT____VdfgRegularize_h8eba6f27_0_19;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__io_axi_aw_id;
        CData/*3:0*/ CpuTop__DOT__axiSram__DOT__io_axi_w_strb;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__rvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__arFire;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__awIdReg;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__awFullReg;
        CData/*3:0*/ CpuTop__DOT__axiSram__DOT__wStrbReg;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__wFullReg;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__bvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__awFire;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__wFire;
        CData/*3:0*/ CpuTop__DOT__axiSram__DOT__writeStrb;
        CData/*0:0*/ CpuTop__DOT__axiSram__DOT__writeFire;
        CData/*3:0*/ CpuTop__DOT__axiUart__DOT__io_axi_w_strb;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__rvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__awFullReg;
        CData/*3:0*/ CpuTop__DOT__axiUart__DOT__wStrbReg;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__wFullReg;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__bvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__arFire;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__awFire;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__wFire;
        CData/*3:0*/ CpuTop__DOT__axiUart__DOT__writeStrb;
        CData/*0:0*/ CpuTop__DOT__axiUart__DOT__writeFire;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__rvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__awFullReg;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__wFullReg;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__bvalidReg;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__arFire;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__awFire;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__wFire;
        CData/*0:0*/ CpuTop__DOT__axiClient__DOT__writeFire;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_1;
        CData/*3:0*/ __Vtableidx1;
        CData/*3:0*/ __Vtableidx2;
        CData/*2:0*/ __VdfgRegularize_h6e95ff9d_0_1;
        CData/*1:0*/ __VdfgRegularize_h6e95ff9d_0_2;
        CData/*0:0*/ __Vdly__CpuTop__DOT__axiSram__DOT__awFullReg;
        CData/*0:0*/ __Vdly__CpuTop__DOT__axiSram__DOT__wFullReg;
        CData/*0:0*/ __Vdly__CpuTop__DOT__axiUart__DOT__awFullReg;
        CData/*0:0*/ __Vdly__CpuTop__DOT__axiUart__DOT__wFullReg;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__CpuTop__DOT__axiSram__DOT__writeFire__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__CpuTop__DOT__axiUart__DOT__writeFire__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*11:0*/ CpuTop__DOT__reg_1_csr_addr;
        SData/*15:0*/ CpuTop__DOT__mem__DOT__load_half;
        VL_OUT(io_debug_pc,31,0);
        VL_OUT(io_debug_inst,31,0);
        VL_OUTW(io_debug_regs_flat,1023,0,32);
        VL_OUT(io_si_pc,31,0);
        VL_OUT(io_si_inst,31,0);
        IData/*31:0*/ CpuTop__DOT___mem_io_out_bits_wb_data;
    };
    struct {
        IData/*31:0*/ CpuTop__DOT___exu_io_out_bits_csr_rdata;
        IData/*31:0*/ CpuTop__DOT___idu_io_out_bits_alu_b;
        IData/*31:0*/ CpuTop__DOT___idu_io_out_bits_mem_wdata;
        IData/*31:0*/ CpuTop__DOT___idu_io_out_bits_csr_wdata;
        IData/*31:0*/ CpuTop__DOT__reg_pc;
        IData/*31:0*/ CpuTop__DOT__reg_inst;
        IData/*31:0*/ CpuTop__DOT__reg_1_pc;
        IData/*31:0*/ CpuTop__DOT__reg_1_inst;
        IData/*31:0*/ CpuTop__DOT__reg_1_alu_a;
        IData/*31:0*/ CpuTop__DOT__reg_1_alu_b;
        IData/*31:0*/ CpuTop__DOT__reg_1_mem_wdata;
        IData/*31:0*/ CpuTop__DOT__reg_1_csr_wdata;
        IData/*31:0*/ CpuTop__DOT__reg_1_csr_zimm;
        IData/*31:0*/ CpuTop__DOT__reg_2_pc;
        IData/*31:0*/ CpuTop__DOT__reg_2_inst;
        IData/*31:0*/ CpuTop__DOT__reg_2_alu_result;
        IData/*31:0*/ CpuTop__DOT__reg_2_mem_addr;
        IData/*31:0*/ CpuTop__DOT__reg_2_load_addr;
        IData/*31:0*/ CpuTop__DOT__reg_2_mem_wdata;
        IData/*31:0*/ CpuTop__DOT__reg_2_pc_plus4;
        IData/*31:0*/ CpuTop__DOT__reg_2_csr_rdata;
        IData/*31:0*/ CpuTop__DOT__reg_3_pc;
        IData/*31:0*/ CpuTop__DOT__reg_3_inst;
        IData/*31:0*/ CpuTop__DOT__reg_3_wb_data;
        IData/*31:0*/ CpuTop__DOT__ifu__DOT__pc;
        IData/*31:0*/ CpuTop__DOT__ifu__DOT__reqPcReg;
        IData/*31:0*/ CpuTop__DOT__ifu__DOT__outPcReg;
        IData/*31:0*/ CpuTop__DOT__ifu__DOT__outInstReg;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__immI;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__io_rdata1;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__io_rdata2;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_1;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_2;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_3;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_4;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_5;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_6;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_7;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_8;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_9;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_10;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_11;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_12;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_13;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_14;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_15;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_16;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_17;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_18;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_19;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_20;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_21;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_22;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_23;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_24;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_25;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_26;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_27;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_28;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_29;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_30;
        IData/*31:0*/ CpuTop__DOT__idu__DOT__regfile__DOT__regs_31;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__io_fwd_wb_data;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__alu__DOT__io_out;
    };
    struct {
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mstatus;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mstatush;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mepc;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mcause;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mtvec;
        IData/*31:0*/ CpuTop__DOT__exu__DOT__csr__DOT__casez_tmp;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_pc;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_inst;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_alu_result;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_mem_addr;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_load_addr;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_mem_wdata;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_pc_plus4;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__reqReg_csr_rdata;
        IData/*31:0*/ CpuTop__DOT__mem__DOT__mem_rdata;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__io_mem_ar_addr;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_ar_addr;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_r_data;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__io_axi_aw_addr;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__readAddrReg;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__awAddrReg;
        IData/*31:0*/ CpuTop__DOT__axiArbiter__DOT__wDataReg;
        IData/*31:0*/ CpuTop__DOT__xbar__DOT__readAddrReg;
        IData/*31:0*/ CpuTop__DOT__xbar__DOT__awAddrReg;
        IData/*31:0*/ CpuTop__DOT__xbar__DOT__wDataReg;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT__io_axi_aw_addr;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT__io_axi_w_data;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT___paddrRead_data;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT__rdataReg;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT__awAddrReg;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT__wDataReg;
        IData/*31:0*/ CpuTop__DOT__axiSram__DOT____Vcellinp__paddrWrite__len;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT__io_axi_aw_addr;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT__io_axi_w_data;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT___paddrRead_data;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT__rdataReg;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT__awAddrReg;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT__wDataReg;
        IData/*31:0*/ CpuTop__DOT__axiUart__DOT____Vcellinp__paddrWrite__len;
        IData/*31:0*/ CpuTop__DOT__axiClient__DOT__io_axi_ar_addr;
        IData/*31:0*/ CpuTop__DOT__axiClient__DOT__rdataReg;
        IData/*31:0*/ __Vfunc_CpuTop__DOT__axiSram__DOT__paddrRead__DOT__paddr_read__0__Vfuncout;
        IData/*31:0*/ __Vfunc_CpuTop__DOT__axiUart__DOT__paddrRead__DOT__paddr_read__2__Vfuncout;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ CpuTop__DOT__exu__DOT__csr__DOT__mcycle_64;
        QData/*63:0*/ CpuTop__DOT__exu__DOT__csr__DOT___mcycle_64_T;
        QData/*63:0*/ CpuTop__DOT__axiClient__DOT__mtime;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    VCpuTop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    VCpuTop___024root(VCpuTop__Syms* symsp, const char* namep);
    ~VCpuTop___024root();
    VL_UNCOPYABLE(VCpuTop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
